name: iv-plotter

services:
  iv-plotter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: sosim-iv-plotter:latest
    ports:
      - "8050:8050"
    restart: unless-stopped
